title: GH for Canberra CSAs and Rob
description: Get started with Issues Projects Actions and Code
template:
  repo: csa-github-lab
  name: csa-lab2
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Create a project board to view your work
    description: Create a project board to view your work
    event: project.created
    actions:
      - type: gate
        left: '%payload.project.name%'
        operator: ===
        right: Project1
        else:
          type: respond
          with: 01_try-again.md
      - type: respond
        with: 01_nice-work.md
