title: # GitHub for Canberra Cloud Solution Architects (and Rob)
tagline: # Short workshop to celebrate Microsoft Learning Day
description: # Get started with Issues, Projects, Actions and Code

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     # csa-github-lab
  repo:     # csa-github-lab

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: # the type of action, full list at https://lab.github.com/docs/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: Create a project board to view your work
- title: Create a project board to view your work
  description: # a description of the step, shown to the learner in the course progress page
  event: project
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: Create an issue to show on your board automatically
# - title: Create an issue to show on your board automatically
#  description: # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: Move your issue to the done column
# - title: Move your issue to the done column
#  description: # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: Create a new branch
# - title: Create a new branch
#  description: # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: Add some "code", commit and create a PR
# - title: Add some "code", commit and create a PR
#  description: # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 6: Complete the PR and see the "card" move in the project board 
# - title: Complete the PR and see the "card" move in the project board 
#  description: # a description of the step, shown to the learner in the course progress page
#  event: # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

