title: GH for Canberra CSAs and Rob
tagline: Short workshop to celebrate Microsoft Learning Day
description: 'Get started with Issues, Projects, Actions and Code'
template:
    name: csa-lab2
    repo: csa-github-lab
before:
  - type: respond
    with: 01_first-response.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: Create a project board to view your work
- title: Create a project board to view your work
  description: Create a project board to view your work # a description of the step, shown to the learner in the course progress page
  event: project.created
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.project.name%'
    operator: ===
    right: "Project1"
    else:
      type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md

# Step 2: Create an issue to show on your board automatically
- title: Create an issue to show on your board automatically
  description: Create an issue to show on your board automatically
  event: issues
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.project.name%'
    operator: ===
    right: "Project1"
    else:
      type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md

# Step 3: Move your issue to the done column
- title: Move your issue to the done column
  description: Move your issue to the done column
  event: project_card.moved # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.project.name%'
    operator: ===
    right: "Project1"
    else:
      type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md

# Step 4: Create a new branch
- title: Create a new branch
  description: Create a new branch
  event: create # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.project.name%'
    operator: ===
    right: "Project1"
    else:
      type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md

# Step 5: Add some "code", commit and create a PR
- title: Add some "code", commit and create a PR
  description: Add some "code", commit and create a PR # a description of the step, shown to the learner in the course progress page
  event: pull_request.opened # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.project.name%'
    operator: ===
    right: "Project1"
    else:
      type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md

# Step 6: Complete the PR and see the "card" move in the project board 
- title: Complete the PR and see the "card" move in the project board 
  description: Complete the PR and see the "card" move in the project board  # a description of the step, shown to the learner in the course progress page
  event: pull_request.closed # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.project.name%'
    operator: ===
    right: "Project1"
    else:
      type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md
